version: '2'

services:

### Applications Code Container #############################

    applications:
      image: tianon/true
      volumes:
        - ./:/var/www

### Workspace Utilities Container ###########################

    workspace:
      build:
        context: ./laradock/workspace
        args:
          - INSTALL_XDEBUG=false
          - INSTALL_BLACKFIRE=false
          - INSTALL_SOAP=false
          - INSTALL_MONGO=false
          - INSTALL_MSSQL=false
          - INSTALL_NODE=true
          - INSTALL_YARN=false
          - INSTALL_DRUSH=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_V8JS=false
          - COMPOSER_GLOBAL_INSTALL=false
          - INSTALL_WORKSPACE_SSH=false
          - INSTALL_LARAVEL_ENVOY=false
          - INSTALL_LARAVEL_INSTALLER=false
          - INSTALL_DEPLOYER=true
          - INSTALL_LINUXBREW=false
          - INSTALL_MC=false
          - PUID=1000
          - PGID=1000
          - NODE_VERSION=stable
          - YARN_VERSION=latest
          - TZ=CEST
          - BLACKFIRE_CLIENT_ID=
          - BLACKFIRE_CLIENT_TOKEN=
        dockerfile: "Dockerfile-71"
      volumes_from:
        - applications
      extra_hosts:
        - "dockerhost:10.0.75.1"
      ports:
        - "2203:22"
      tty: true
      networks:
        - frontend
        - backend

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./laradock/php-fpm
        args:
          - INSTALL_XDEBUG=false
          - INSTALL_BLACKFIRE=false
          - INSTALL_SOAP=false
          - INSTALL_MONGO=false
          - INSTALL_MSSQL=false
          - INSTALL_ZIP_ARCHIVE=false
          - INSTALL_BCMATH=false
          - INSTALL_PHPREDIS=false
          - INSTALL_MEMCACHED=false
          - INSTALL_OPCACHE=false
          - INSTALL_EXIF=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_MYSQLI=false
          - INSTALL_TOKENIZER=false
          - INSTALL_INTL=false
          - INSTALL_GHOSTSCRIPT=false
          - INSTALL_LDAP=false
          - INSTALL_SWOOLE=false
        dockerfile: "Dockerfile-71"
      volumes_from:
        - applications
      volumes:
        - ./laradock/php-fpm/php71.ini:/usr/local/etc/php/php.ini
      expose:
        - "9000"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:10.0.75.1"
      environment:
        - PHP_IDE_CONFIG="serverName=sudoku"
      networks:
        - backend

### Apache Server Container #################################

    apache2:
      build:
        context: ./laradock/apache2
        args:
          - PHP_SOCKET="php-fpm:9000"
      volumes_from:
        - applications
      volumes:
        - ./storage/docker/apache2/logs:/var/log/apache2
        - ./laradock/apache2/sites:/etc/apache2/sites-available
      ports:
        - "8004:80"
        - "4434:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### MySQL Container #########################################

    mysql:
      build:
        context: ./laradock/mysql
      environment:
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - ./storage/docker/mysql:/var/lib/mysql
        - ./laradock/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "3304:3306"
      networks:
        - backend

### Mailhog Container #########################################

    mailhog:
      build: ./laradock/mailhog
      ports:
        - "8029:8025"
      networks:
        - backend
        - frontend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
